In [25]:
### 26 Feb Assignment

#### Consider the below code to answer further questions:

In [11]:
import numpy as np
list_ = ['1' , '2' , '3' , '4' , '5' ]
array_list = np.array(list_)

#### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

Yes, there is a difference in the data types of the list_ variable and the array_list variable. The elements in list_ are of type string, while array_list is a NumPy array, and its elements will be of type numpy.str_.

Here's the code to print the data types of both variables:

In [12]:
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


In [13]:
print("Data type of list_:", type(list_[0]))
print("Data type of array_list:", type(array_list[0]))

Data type of list_: <class 'str'>
Data type of array_list: <class 'numpy.str_'>


#### Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [14]:
# Data type of each element in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Data type of each element in array_list
print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


#### Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

#### Will there be any difference in the data type of the elements present in both the variables, list_ and array_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

In [15]:
array_list = np.array(object = list_, dtype = int)

In [16]:
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Data type of each element in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Data type of each element in array_list
print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


#### Consider the below code to answer further questions:

In [17]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

#### Q4. Write a code to find the following characteristics of variable, num_array:
* shape
*  size

In [18]:
# (i) Shape of the array
shape_of_array = num_array.shape
print("Shape of num_array:", shape_of_array)

# (ii) Size of the array
size_of_array = num_array.size
print("Size of num_array:", size_of_array)

Shape of num_array: (2, 3)
Size of num_array: 6


#### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [20]:
import numpy as np

# Create a 3x3 matrix of zeros
zero_matrix = np.zeros((3, 3))

print("3x3 Matrix of Zeros:")
print(zero_matrix)

3x3 Matrix of Zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [24]:
import numpy as np

# Create a 3x3 identity matrix
eye_matrix = np.eye(5)

print("5x5 Identity Matrix:")
print(eye_matrix)

print(eye_matrix.shape)

5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
(5, 5)
